// scripts/save-server.cjs
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 3001;
const TARGET_FILE = path.join(__dirname, '../src/data/locations.js');

const server = http.createServer((req, res) => {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    res.statusCode = 204;
    res.end();
    return;
  }

  // Handle Save
  if (req.method === 'POST' && req.url === '/save') {
    let body = '';
    req.on('data', chunk => { body += chunk.toString(); });
    req.on('end', () => {
      try {
        let data = JSON.parse(body);

        // Sanitize data: Remove any temporary preview URLs (blob links) before saving to disk
        const sanitizeData = (obj) => {
          if (Array.isArray(obj)) {
            obj.forEach(sanitizeData);
          } else if (obj && typeof obj === 'object') {
            Object.keys(obj).forEach(key => {
              if (key.toLowerCase().endsWith('previewurl')) {
                delete obj[key];
              } else {
                sanitizeData(obj[key]);
              }
            });
          }
        };
        sanitizeData(data);

        const code = `// src/data/locations.js
// This file is automatically generated by the Tour Creator.
// Do not edit this file manually unless you know what you are doing.

// Each location has a unique ID, a display name, and a list of viewpoints.
// Each viewpoint has an ID, name, description, image path, rotation offsets,
// minimap positions, and a list of interactive hotspots.
export const LOCATIONS = ${JSON.stringify(data, null, 2)};

// Helper function to determine if a hotspot is for internal navigation within the same room.
export const isHotspotInternal = (hotspot, currentViewpointId) => {
  if (!hotspot || !currentViewpointId) return false;
  const currentRoomId = currentViewpointId.split('_')[0];
  return hotspot.target === currentRoomId;
};
`;

        fs.writeFileSync(TARGET_FILE, code, 'utf8');
        console.log(`[SaveServer] Successfully updated ${TARGET_FILE}`);
        
        res.statusCode = 200;
        res.end(JSON.stringify({ success: true, message: 'File updated successfully' }));
      } catch (err) {
        console.error('[SaveServer] Error:', err);
        res.statusCode = 500;
        res.end(JSON.stringify({ success: false, error: err.message }));
      }
    });
  } else {
    res.statusCode = 404;
    res.end();
  }
});

server.listen(PORT, () => {
  console.log(`[SaveServer] Running on http://localhost:${PORT}`);
  console.log(`[SaveServer] Targeting: ${TARGET_FILE}`);
});
